# Generated by Django 6.0 on 2025-12-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('categoria', models.CharField(choices=[('bebidas', 'bebidas'), ('doces', 'doces'), ('salgados', 'salgados'), ('pratos', 'pratos'), ('outros', 'outros')], default='bebidas', max_length=40)),
                ('descricao', models.TextField(default='Sem descrição', max_length=300)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='temp_uploads')),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('promocao', models.BooleanField(default=False)),
                ('hora_criacao', models.TimeField(auto_now_add=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
